# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manuel Kansy
tagline: Academic Website of Manuel Kansy
email: manuel.kansy@inf.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD student at ETH Zurich in cooperation with DisneyResearch|Studios  
  focusing on image and video generation, especially for human faces.
domain: mkansy.github.io
url: https://mkansy.github.io
baseurl: 
social:
  - https://scholar.google.com/citations?user=DDNXeM8AAAAJ&hl
  - https://www.linkedin.com/in/manuel-kansy/
  - https://twitter.com/manuelkansy
google_site_verification:
plugins:
  - jekyll-seo-tag
author:
  name: Manuel Kansy
  url: https://mkansy.github.io
  twitter: ManuelKansy

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
